In [3]:
import numpy as np


In [4]:
from google.colab import files

In [5]:
import pandas as pd

sheet_id = '1AmoFVobSFQ7MloeR6dlAlqpAERi3c5mPdACNTPhSsQ4'
sheet_gid = '748384306'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={sheet_gid}'


In [6]:
df = pd.read_csv(url)

In [7]:
df

R comapny       R comapny.1     R comapny.2  R comapny.3  \
0              Domain  Linked Followers  Employee Count      Revenue   
1       connecthr.com                10               1       457518   
2         birdeye.com                12              17      4228206   
3       photosonic.ai                28             NaN          NaN   
4           eicher.in                35              28     14602868   
..                ...               ...             ...          ...   
169          sony.com          [unknown             955    454146430   
170         tidio.com          [unknown             159     72745362   
171    useinsider.com          [unknown            1161    531178398   
172    volvogroup.com          [unknown           68389  35666983559   
173  zstack-cloud.com          [unknown              24     12245064   

                  R comapny.4  \
0                          ID   
1    57ce44d0e4b0c30140e59664   
2    572b572be4b048f8cb592543   
3                         NaN   
4    57ce44ede4b0c30140e69ee3   
..                        ...   
169  57b76843d4c665ceaa811be3   
170  5b48bc81ecc1545eea2adaf7   
171  57ce626de4b0c30141f2fcdd   
172  57ce619ee4b0c30141ebc435   
173  61fcdde246e0fb00014d693b   

                                         Adapt Company  \
0                                          Specialties   
1                                                  NaN   
2    Reputation marketing, Reviews management, Ente...   
3                                                  NaN   
4    Commercial Vehicles, Trucks, Buses, and Applic...   
..                                                 ...   
169                                                NaN   
170                                                NaN   
171                                                NaN   
172                                                NaN   
173                                                NaN   

    R Company or Adapt Company's Location  
0                                 Country  
1                           United States  
2                           United States  
3                                     NaN  
4                                   India  
..                                    ...  
169                                 Japan  
170                                   NaN  
171                                 China  
172                                 China  
173                                   NaN  

[174 rows x 7 columns]

In [8]:
df_filtered = df.dropna(axis=0, how='any')

In [9]:
df=df_filtered

In [10]:
df

R comapny       R comapny.1     R comapny.2  \
0                  Domain  Linked Followers  Employee Count   
2             birdeye.com                12              17   
4               eicher.in                35              28   
11           synerion.com               595              34   
17              deere.com              1656              10   
19             uplead.com              2704              70   
20               reply.io              2775             106   
23            manitou.com              4917             109   
29               mips.com              8179             501   
31              owler.com              8531             220   
32        powericaltd.com              8654             977   
33             vitally.io              8990              56   
35           liebherr.com              9982             202   
36         syncfusion.com             11897            1286   
39       alibabacloud.com             14894              49   
41     datavirtuality.com             15821              39   
43            particle.io             16752             151   
44      clientsuccess.com             18074              31   
45               ebay.com             18315            1249   
46             upgrad.com             18828             105   
47         saleshandy.com             19014              58   
49              coveo.com             24220             786   
50  workforcesoftware.com             25405             751   
51              aeris.com             25505             243   
52              study.com             27115            2275   
54    constantcontact.com             31618            1125   
56            cognism.com             38373             430   
58             podium.com             48023            1220   
59            netgear.com             49333            1204   
60             denodo.com             49743             643   
61             paycor.com             50664            2587   
62             rambus.com             51174            1007   
63       korewireless.com             51209             582   
64               pendo.io             53013             945   
65           intercom.com             61245            1373   
66         sanyglobal.com             61605            4666   
67           prodrive.com             63863             422   
69       digitalocean.com             73724            1260   
70             lenovo.com             74793             684   
72           zoominfo.com             95512            3781   
73          gainsight.com            102143            1300   
76           infineon.com            126923            2855   
77              terex.com            143935            6622   
78          panasonic.com            144795            2012   
79           payoneer.com            145749            2640   
80             paycom.com            154073            5518   
81    extremenetworks.com            174624            3627   
82          mailchimp.com            177304            1625   
83               payu.com            189414            2767   
84              denso.com            198065           15268   
86               qlik.com            218966            2713   
87             rogers.com            219159           25088   
88           millicom.com            222730           23834   
90       alibabagroup.com            235067            3887   
91            komatsu.com            236050            7900   

                  R comapny.3               R comapny.4  \
0                     Revenue                        ID   
2                     4228206  572b572be4b048f8cb592543   
4                    14602868  57ce44ede4b0c30140e69ee3   
11                   15555612  57499c4fe4b06a6a3b071b08   
17                    4648060  578fb1f4e4b0e57a1065ae1d   
19                   32026260  5a7084eb383b2c2a9cf80e72   
20                   48496908  57ce3714e4b0c30140701eeb   
23             

In [11]:
df['CRevenue'] = df['R comapny.3'].str.replace('[^0-9]', '', regex=True)

<ipython-input-11-e67e3456825c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CRevenue'] = df['R comapny.3'].str.replace('[^0-9]', '', regex=True)


In [12]:
df

R comapny       R comapny.1     R comapny.2  \
0                  Domain  Linked Followers  Employee Count   
2             birdeye.com                12              17   
4               eicher.in                35              28   
11           synerion.com               595              34   
17              deere.com              1656              10   
19             uplead.com              2704              70   
20               reply.io              2775             106   
23            manitou.com              4917             109   
29               mips.com              8179             501   
31              owler.com              8531             220   
32        powericaltd.com              8654             977   
33             vitally.io              8990              56   
35           liebherr.com              9982             202   
36         syncfusion.com             11897            1286   
39       alibabacloud.com             14894              49   
41     datavirtuality.com             15821              39   
43            particle.io             16752             151   
44      clientsuccess.com             18074              31   
45               ebay.com             18315            1249   
46             upgrad.com             18828             105   
47         saleshandy.com             19014              58   
49              coveo.com             24220             786   
50  workforcesoftware.com             25405             751   
51              aeris.com             25505             243   
52              study.com             27115            2275   
54    constantcontact.com             31618            1125   
56            cognism.com             38373             430   
58             podium.com             48023            1220   
59            netgear.com             49333            1204   
60             denodo.com             49743             643   
61             paycor.com             50664            2587   
62             rambus.com             51174            1007   
63       korewireless.com             51209             582   
64               pendo.io             53013             945   
65           intercom.com             61245            1373   
66         sanyglobal.com             61605            4666   
67           prodrive.com             63863             422   
69       digitalocean.com             73724            1260   
70             lenovo.com             74793             684   
72           zoominfo.com             95512            3781   
73          gainsight.com            102143            1300   
76           infineon.com            126923            2855   
77              terex.com            143935            6622   
78          panasonic.com            144795            2012   
79           payoneer.com            145749            2640   
80             paycom.com            154073            5518   
81    extremenetworks.com            174624            3627   
82          mailchimp.com            177304            1625   
83               payu.com            189414            2767   
84              denso.com            198065           15268   
86               qlik.com            218966            2713   
87             rogers.com            219159           25088   
88           millicom.com            222730           23834   
90       alibabagroup.com            235067            3887   
91            komatsu.com            236050            7900   

                  R comapny.3               R comapny.4  \
0                     Revenue                        ID   
2                     4228206  572b572be4b048f8cb592543   
4                    14602868  57ce44ede4b0c30140e69ee3   
11                   15555612  57499c4fe4b06a6a3b071b08   
17                    4648060  578fb1f4e4b0e57a1065ae1d   
19                   32026260  5a7084eb383b2c2a9cf80e72   
20                   48496908  57ce3714e4b0c30140701eeb   
23             

In [13]:
df.drop('R comapny.3',axis=1,inplace=True)

<ipython-input-13-1a4ce2db27cd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('R comapny.3',axis=1,inplace=True)


In [14]:
stop_word='and'
df['Adapt Company'] = df['Adapt Company'].str.replace(f', {stop_word}', ',', regex=False)

<ipython-input-14-c1e73c6869bd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Adapt Company'] = df['Adapt Company'].str.replace(f', {stop_word}', ',', regex=False)


In [15]:
pd.set_option('display.max_colwidth', None)

In [23]:
df = df.reset_index()
df.drop('index',axis=1,inplace=True)
df


level_0              R comapny       R comapny.1     R comapny.2  \
0         0                 Domain  Linked Followers  Employee Count   
1         1            birdeye.com                12              17   
2         2              eicher.in                35              28   
3         3           synerion.com               595              34   
4         4              deere.com              1656              10   
5         5             uplead.com              2704              70   
6         6               reply.io              2775             106   
7         7            manitou.com              4917             109   
8         8               mips.com              8179             501   
9         9              owler.com              8531             220   
10       10        powericaltd.com              8654             977   
11       11             vitally.io              8990              56   
12       12           liebherr.com              9982             202   
13       13         syncfusion.com             11897            1286   
14       14       alibabacloud.com             14894              49   
15       15     datavirtuality.com             15821              39   
16       16            particle.io             16752             151   
17       17      clientsuccess.com             18074              31   
18       18               ebay.com             18315            1249   
19       19             upgrad.com             18828             105   
20       20         saleshandy.com             19014              58   
21       21              coveo.com             24220             786   
22       22  workforcesoftware.com             25405             751   
23       23              aeris.com             25505             243   
24       24              study.com             27115            2275   
25       25    constantcontact.com             31618            1125   
26       26            cognism.com             38373             430   
27       27             podium.com             48023            1220   
28       28            netgear.com             49333            1204   
29       29             denodo.com             49743             643   
30       30             paycor.com             50664            2587   
31       31             rambus.com             51174            1007   
32       32       korewireless.com             51209             582   
33       33               pendo.io             53013             945   
34       34           intercom.com             61245            1373   
35       35         sanyglobal.com             61605            4666   
36       36           prodrive.com             63863             422   
37       37       digitalocean.com             73724            1260   
38       38             lenovo.com             74793             684   
39       39           zoominfo.com             95512            3781   
40       40          gainsight.com            102143            1300   
41       41           infineon.com            126923            2855   
42       42              terex.com            143935            6622   
43       43          panasonic.com            144795            2012   
44       44           payoneer.com            145749            2640   
45       45             paycom.com            154073            5518   
46       46    extremenetworks.com            174624            3627   
47       47          mailchimp.com            177304            1625   
48       48               payu.com            189414            2767   
49       49              denso.com            198065           15268   
50       50               qlik.com            218966            2713   
51       51             rogers.com            219159           25088   
52       52           millicom.com            222730           23834   
53       53       alibabagroup.com            235067            3887   
54       54            komatsu.com          

In [24]:
df.rename(columns={'level_0': 'indices'}, inplace=True)

In [25]:
df.shape

(55, 8)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initializing  CountVectorizer with English stop words
vectorizer = TfidfVectorizer()
count_matrix = vectorizer.fit_transform(df['Adapt Company'])
feature_names = vectorizer.get_feature_names_out()

#shape of the count matrix
print("Shape of count matrix:", count_matrix.shape)
print(count_matrix.toarray())

# Display the vocabulary
print(feature_names)

Shape of count matrix: (55, 404)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['abm' 'absence' 'acceleration' 'access' 'account' 'accuracy'
 'acquisition' 'administration' 'aerial' 'aeronautics' 'aerospace'
 'aftermarket' 'agile' 'agriculture' 'ai' 'alternative' 'analysis'
 'analytics' 'and' 'appliances' 'applicant' 'application' 'articulated'
 'as' 'asp' 'attendance' 'auto' 'automatic' 'automation' 'automotive'
 'b2b' 'backhoe' 'bank' 'barcoding' 'based' 'benchmarking' 'benefits' 'bi'
 'big' 'border' 'broadband' 'broadcasting' 'build' 'builds' 'buses'
 'business' 'cable' 'capital' 'car' 'card' 'cards' 'cash' 'center'
 'certified' 'chain' 'charging' 'chassis' 'chat' 'china' 'churn'
 'cleaning' 'client' 'climate' 'cloud' 'cold' 'commerce' 'commercial'
 'communication' 'communications' 'communities' 'company' 'compensation'
 'competitive' 'competitor' 'compliance' 'components' '

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
word_similarity = cosine_similarity(count_matrix, count_matrix)

# Display the similarity matrix
print("Similarity matrix:")
print(word_similarity)

Similarity matrix:
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.06368446]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.06368446 0.         ... 0.         0.         1.        ]]


In [28]:
df= df.reset_index()
index = pd.Series(df['indices'].values, index=df['R comapny'])


In [50]:
def get_recommendations(company_name, cosine_sim=word_similarity):
    # Find the index of the company in the DataFrame
    idx = df[df['R comapny'] == company_name].index[0]

    # Get the pairwise similarity scores of all companies with this company
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the companies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the top 10 most similar companies
    sim_scores = sim_scores[1:11]

    # Get the indices of the similar companies
    company_indices = [i[0] for i in sim_scores]

    # Get the similarity scores of the top 10 most similar companies
    similarity_scores = [i[1] for i in sim_scores]

    # Return the top 10 most similar companies along with their similarity scores
    return list(zip(df['R comapny'].iloc[company_indices], similarity_scores))

# Example usage
company_name = 'uplead.com'
recommendations = get_recommendations(company_name)
for company, score in recommendations:
    print(f"Company: {company}, Similarity Score: {score}")


Company: mailchimp.com, Similarity Score: 0.44640948476403897
Company: constantcontact.com, Similarity Score: 0.3798826250976981
Company: reply.io, Similarity Score: 0.37139683361118764
Company: cognism.com, Similarity Score: 0.3531004708365195
Company: zoominfo.com, Similarity Score: 0.35055869412923635
Company: vitally.io, Similarity Score: 0.32127365817795284
Company: millicom.com, Similarity Score: 0.15520568134900103
Company: denodo.com, Similarity Score: 0.1501146288372178
Company: datavirtuality.com, Similarity Score: 0.13145287631596297
Company: alibabacloud.com, Similarity Score: 0.11690651723730837


In [32]:
df

index  indices              R comapny       R comapny.1     R comapny.2  \
0       0        0                 Domain  Linked Followers  Employee Count   
1       1        1            birdeye.com                12              17   
2       2        2              eicher.in                35              28   
3       3        3           synerion.com               595              34   
4       4        4              deere.com              1656              10   
5       5        5             uplead.com              2704              70   
6       6        6               reply.io              2775             106   
7       7        7            manitou.com              4917             109   
8       8        8               mips.com              8179             501   
9       9        9              owler.com              8531             220   
10     10       10        powericaltd.com              8654             977   
11     11       11             vitally.io              8990              56   
12     12       12           liebherr.com              9982             202   
13     13       13         syncfusion.com             11897            1286   
14     14       14       alibabacloud.com             14894              49   
15     15       15     datavirtuality.com             15821              39   
16     16       16            particle.io             16752             151   
17     17       17      clientsuccess.com             18074              31   
18     18       18               ebay.com             18315            1249   
19     19       19             upgrad.com             18828             105   
20     20       20         saleshandy.com             19014              58   
21     21       21              coveo.com             24220             786   
22     22       22  workforcesoftware.com             25405             751   
23     23       23              aeris.com             25505             243   
24     24       24              study.com             27115            2275   
25     25       25    constantcontact.com             31618            1125   
26     26       26            cognism.com             38373             430   
27     27       27             podium.com             48023            1220   
28     28       28            netgear.com             49333            1204   
29     29       29             denodo.com             49743             643   
30     30       30             paycor.com             50664            2587   
31     31       31             rambus.com             51174            1007   
32     32       32       korewireless.com             51209             582   
33     33       33               pendo.io             53013             945   
34     34       34           intercom.com             61245            1373   
35     35       35         sanyglobal.com             61605            4666   
36     36       36           prodrive.com             63863             422   
37     37       37       digitalocean.com             73724            1260   
38     38       38             lenovo.com             74793             684   
39     39       39           zoominfo.com             95512            3781   
40     40       40          gainsight.com            102143            1300   
41     41       41           infineon.com            126923            2855   
42     42       42              terex.com            143935            6622   
43     43       43          panasonic.com            144795            2012   
44     44       44           payoneer.com            145749            2640   
45     45       45             paycom.com            154073            5518   
46     46       46    extremenetworks.com            174624            3627   
47     47       47          mailchimp.com            177304            1625   
48     48       48               payu.com            189414            2767   
49     49       49              denso.com            1

In [39]:
!pip install annoy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.5/647.5 kB 15.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.3-cp310-cp310-linux_x86_64.whl size=550736 sha256=bb557c3963a1659a6d275754803d33e8d77345f2470aa247f273efae82ad33ab
  Stored in directory: /root/.cache/pip/wheels/64/8a/da/f714bcf46c5efdcfcac0559e63370c21abe961c48e3992465a
Successfully built annoy


In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
from annoy import AnnoyIndex
import numpy as np

In [41]:
# Initialize Annoy index
annoy_index = AnnoyIndex(count_matrix.shape[1], 'angular')

In [43]:
for i in range(55):
    embedding = count_matrix[i].toarray()[0]
    annoy_index.add_item(i, embedding)

# Build the Annoy index
annoy_index.build(10)


True

In [56]:
# def get_similar_domains(company_name, n=10):
#     idx = df[df['R comapny'] == company_name].index[0]
#     similar_indices, similarity_scores = annoy_index.get_nns_by_item(idx, n+1, include_distances=True)  # Include distances for similarity scores
#     similar_indices = similar_indices[1:]  # Exclude the first item (itself)
#     similarity_scores = similarity_scores[1:]  # Exclude the first item (itself)
#     similar_domains = df.iloc[similar_indices][['R comapny','Adapt Company']]
#     similar_domains['Similarity Score'] = similarity_scores
#     similar_domains = similar_domains.sort_values(by='Similarity Score', ascending=False)  # Sort by similarity score in descending order
#     pd.set_option('display.max_colwidth', None)
#     return similar_domains

# # Example: Get similar items for 'electrix.us'
# similar_domains = get_similar_domains('uplead.com')
# print(similar_domains)
def get_similar_domains(company_name, n=10):
    idx = df[df['R comapny'] == company_name].index[0]
    similar_indices, similarity_scores = annoy_index.get_nns_by_item(idx, n+1, include_distances=True)  # Include distances for similarity scores
    similar_indices = similar_indices[1:]  # Exclude the first item (itself)
    similarity_scores = similarity_scores[1:]  # Exclude the first item (itself)
    similar_domains = df.iloc[similar_indices][['R comapny','Adapt Company']]
    similar_domains['Similarity Score'] = similarity_scores
    similar_domains = similar_domains.sort_values(by='Similarity Score', ascending=True)  # Sort by similarity score in descending order
    pd.set_option('display.max_colwidth', None)
    return similar_domains

# Example: Get similar items for 'electrix.us'
similar_domains = get_similar_domains('uplead.com')
for index, row in similar_domains.iterrows():
    print(f"Company: {row['R comapny']}, Similarity Score: {row['Similarity Score']}")


Company: mailchimp.com, Similarity Score: 1.0522266626358032
Company: constantcontact.com, Similarity Score: 1.1136583089828491
Company: reply.io, Similarity Score: 1.121252179145813
Company: cognism.com, Similarity Score: 1.1374528408050537
Company: zoominfo.com, Similarity Score: 1.1396852731704712
Company: vitally.io, Similarity Score: 1.165097713470459
Company: millicom.com, Similarity Score: 1.2998417615890503
Company: denodo.com, Similarity Score: 1.3037525415420532
Company: datavirtuality.com, Similarity Score: 1.3179887533187866
Company: alibabacloud.com, Similarity Score: 1.3289796113967896
